//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceOrder
    {
        public int order_id { get; set; }
        public Nullable<int> cus_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
