//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DataBasedemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int error_id { get; set; }
        public string error_msg { get; set; }
        public Nullable<System.DateTime> error_time { get; set; }
    }
}
