//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DataBasedemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int student_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<int> age { get; set; }
        public string grade { get; set; }
        public string email { get; set; }
    }
}
